import React, {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, Users, Building2, Phone, Layers, Bot, Settings, LayoutDashboard, Plus, ArrowUpRight, Search, LogOut, X, Play, Pause, Square, RefreshCw, Upload, ShieldCheck, CalendarClock} from 'lucide-react';
import {api} from './api';
import './style.css';
type Row = Record<string, any>;
const sections = [['dashboard','Обзор',LayoutDashboard],['campaigns','Кампании',Layers],['contacts','Контакты',Users],['companies','Компании',Building2],['calls','Звонки',Phone],['scenarios','Сценарии',Activity],['agents','Агенты',Bot],['callbacks','Перезвоны',CalendarClock],['settings','Настройки',Settings]] as const;
const labels:Record<string,string>={draft:'Черновик',running:'В работе',paused:'Пауза',stopped:'Остановлена',completed:'Завершено',failed:'Ошибка',new:'Новый',queued:'В очереди',ringing:'Дозвон',answered:'Разговор',cancelled:'Отменён',transferred:'Передан',opted_out:'Отказ',pending:'Запланирован'};
const fmt=(v:string)=>v?new Date(v.endsWith('Z')||/[+-]\d\d:\d\d$/.test(v)?v:v+'Z').toLocaleString('ru-RU'):'—';
function Badge({value}:{value:string}){return <span className={'badge '+value}>{labels[value]||value}</span>}
function App(){
 const [user,setUser]=useState<Row|null>(null),[checking,setChecking]=useState(true),[section,setSection]=useState('dashboard');
 const [rows,setRows]=useState<Row[]>([]),[stats,setStats]=useState<Row>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState('');
 const [modal,setModal]=useState<string|null>(null),[selected,setSelected]=useState<Row|null>(null),[options,setOptions]=useState<Record<string,Row[]>>({});
 const [importFile,setImportFile]=useState<File|null>(null),[preview,setPreview]=useState<Row|null>(null);
 async function load(){if(!user)return;setError('');if(section==='dashboard'){setStats(await api('/dashboard'));setRows(await api('/campaigns'))}else if(section==='settings'){setStats(await api('/settings'));setRows(await api('/backups'))}else setRows(await api('/'+section));}
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{api('/auth/me').then(setUser).catch(()=>{}).finally(()=>setChecking(false))},[]);
 useEffect(()=>{setQuery('');setSelected(null);setRows([]);run(load)},[section,user]);
 async function openForm(){await run(async()=>{const o:Record<string,Row[]>={};for(const p of section==='campaigns'?['scenarios','agents']:section==='contacts'?['companies']:section==='callbacks'?['contacts']:[])o[p]=await api('/'+p);setOptions(o);setModal('create')})}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const body:Row=Object.fromEntries(new FormData(e.currentTarget).entries());
  for(const key of ['max_concurrent','delay_seconds','max_attempts','max_errors','start_hour','end_hour'])if(key in body)body[key]=Number(body[key]);
  if(section==='scenarios')for(const key of ['required_questions','optional_questions','allowed_topics','forbidden_topics'])body[key]=(body[key]||'').split('\n').map((x:string)=>x.trim()).filter(Boolean);
  if(section==='contacts'&&!body.company_id)body.company_id=null;
  if(section==='callbacks')body.scheduled_at=new Date(body.scheduled_at).toISOString();
  await run(async()=>{await api('/'+section,'POST',body);setModal(null);await load()});
 }
 async function inspect(r:Row){await run(async()=>{setSelected(section==='calls'||section==='contacts'?await api('/'+section+'/'+r.id):r);setModal('detail')})}
 async function action(r:Row,a:string){await run(async()=>{await api('/campaigns/'+r.id+'/'+a,'POST');await load()})}
 async function importContacts(commit=false){if(!importFile)return;await run(async()=>{const data=new FormData();data.append('file',importFile);const r=await api('/import/contacts?commit='+commit,'POST',data);setPreview(r);if(commit){setModal(null);setImportFile(null);setPreview(null);await load()}})}
 const canWrite=user?.role!=='viewer';
 if(checking)return <div className="loading">Подключаем операторскую…</div>;
 if(!user)return <div className="login"><div className="login-brand"><div className="logo"><Activity/> AI Caller</div><h1>Разговор начинается<br/>с понимания.</h1><p>Ваши агенты, контакты и история общения<br/>в одной операторской.</p><span className="tag">ЛОКАЛЬНАЯ ПЛАТФОРМА · 0.1</span></div><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{setUser(await api('/auth/login','POST',Object.fromEntries(f.entries())))})}}><span className="eyebrow">РАБОЧЕЕ ПРОСТРАНСТВО</span><h2>Войти в систему</h2><p>Используйте учётную запись из настройки проекта.</p><label>Логин<input name="username" autoComplete="username" required defaultValue="admin"/></label><label>Пароль<input name="password" type="password" autoComplete="current-password" required/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>Войти <ArrowUpRight size={17}/></button><small><ShieldCheck size={14}/> Данные остаются в вашей инфраструктуре.</small></form></div>;
 return <div className="shell"><aside><div className="logo"><Activity/> AI Caller<span>ЛОКАЛЬНО</span></div><div className="workspace"><span className="avatar">A</span><div>Операторская<small>Рабочее пространство</small></div></div><span className="nav-label">УПРАВЛЕНИЕ</span><nav>{sections.filter(x=>x[0]!=='settings'||user.role==='admin').map(([id,title,Icon])=><button key={id} className={section===id?'active':''} onClick={()=>setSection(id)}><Icon size={19}/>{title}</button>)}</nav><div className="aside-bottom"><div className="safe"><ShieldCheck size={17}/> Режим симуляции</div><div className="account"><span className="avatar">{user.username[0].toUpperCase()}</span><div>{user.username}<small>{user.role}</small></div><button title="Выйти" onClick={()=>run(async()=>{await api('/auth/logout','POST');setUser(null)})}><LogOut size={17}/></button></div></div></aside>
 <main><header><span>Рабочее пространство <b>/ {sections.find(x=>x[0]===section)?.[1]}</b></span><span className="connection"><i/> {busy?'Обновление…':'Операторская'}</span></header><div className="content"><div className="page-heading"><div><span className="eyebrow">AI CALLER / ОПЕРАТОРСКАЯ</span><h1>{sections.find(x=>x[0]===section)?.[1]}</h1><p>{section==='dashboard'?'Все разговоры и работа команды — перед вами.':section==='calls'?'История, транскрипции и результат каждого разговора.':'Управляйте данными и готовьте следующий разговор.'}</p></div><div className="actions"><button onClick={()=>run(load)} disabled={busy} title="Обновить"><RefreshCw size={17}/></button>{canWrite&&!['dashboard','calls','settings'].includes(section)&&<button className="primary" onClick={openForm}><Plus size={17}/>Создать</button>}</div></div>
 <div className="notice"><ShieldCheck size={18}/><div><b>Кампании работают в симуляции.</b> SIP и AI требуют отдельной приёмки одиночного звонка.</div></div>{error&&<div className="error" role="alert">{error}</div>}
 {section==='dashboard'&&<><div className="metrics">{[['Контакты',stats.contacts||0,'В вашей базе'],['Звонки сегодня',stats.calls_today||0,'По времени UTC'],['Активные звонки',stats.active_calls||0,'Сейчас в работе'],['Средний разговор',Math.round(stats.average_duration||0)+' с','Завершённые звонки']].map(([label,value,hint])=><div className="metric" key={label}><span>{label}</span><strong>{value}</strong><small>{hint}</small></div>)}</div><div className="section-title"><h2>Кампании</h2><button onClick={()=>setSection('campaigns')}>Все кампании <ArrowUpRight size={16}/></button></div></>}
 {section==='settings'?<><div className="panel"><h2>Конфигурация</h2><p>Секреты задаются в локальном .env. API не возвращает их в браузер.</p><dl>{Object.entries(stats).map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{String(v)}</dd></React.Fragment>)}</dl></div><div className="section-title"><h2>Резервные копии</h2><button className="primary" disabled={busy} onClick={()=>run(async()=>{await api('/backups','POST');await load()})}>Создать копию</button></div><div className="panel">{rows.length?rows.map(r=><p key={r.id}>{fmt(r.created_at)} · <Badge value={r.status}/> {r.filename} {r.error}</p>):<p>Резервных копий пока нет.</p>}</div></>:
 <div className="panel table-panel"><div className="table-tools"><div className="search"><Search size={17}/><input placeholder="Поиск в загруженном списке…" value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{rows.length} записей</span>{section==='contacts'&&canWrite&&<button onClick={()=>{setPreview(null);setImportFile(null);setModal('import')}}><Upload size={16}/> Импорт CSV / XLSX</button>}</div>{rows.length?<div className="table-scroll"><table><thead><tr><th>{section==='calls'?'Звонок':'Название / контакт'}</th><th>Подробности</th><th>Статус</th><th>Создано</th><th/></tr></thead><tbody>{rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())).map(r=><tr key={r.id}><td><button className="row-link" onClick={()=>inspect(r)}>{r.name||r.contact_id?.slice(0,8)||r.id.slice(0,8)}</button>{r.mode&&<small>{r.mode==='simulation'?'Симуляция':'Реальный звонок'}</small>}</td><td>{section==='contacts'?r.phone:section==='calls'?`${Math.round(r.duration_seconds)} с · ${r.end_reason||'—'}`:section==='campaigns'||section==='dashboard'?Object.entries(r.counts||{}).map(([k,v])=>`${labels[k]||k}: ${v}`).join(' · ')||'Контакты не добавлены':section==='callbacks'?fmt(r.scheduled_at):r.goal||r.role||r.notes||'—'}</td><td><Badge value={r.opted_out?'opted_out':r.status||'new'}/></td><td className="date">{fmt(r.created_at)}</td><td><div className="actions">{(section==='campaigns'||section==='dashboard')&&canWrite&&<>{['draft','paused'].includes(r.status)&&<><button title="Добавить контакты" onClick={()=>run(async()=>{setSelected(r);setOptions({contacts:await api('/contacts')});setModal('enroll')})}><Users size={16}/></button><button title="Запустить" disabled={busy} onClick={()=>action(r,'start')}><Play size={16}/></button></>}{r.status==='running'&&<button title="Пауза" disabled={busy} onClick={()=>action(r,'pause')}><Pause size={16}/></button>}{['running','paused','draft'].includes(r.status)&&<button title="Остановить очередь" disabled={busy} onClick={()=>action(r,'stop')}><Square size={15}/></button>}</>}</div></td></tr>)}</tbody></table></div>:<div className="empty"><Layers size={35}/><h3>Здесь появятся ваши данные</h3><p>{section==='dashboard'?'Создайте сценарий, агента и контакты, затем первую кампанию.':'Добавьте первую запись, чтобы начать работу.'}</p>{section==='dashboard'&&<button onClick={()=>setSection('scenarios')}>Создать сценарий <ArrowUpRight size={16}/></button>}</div>}</div>}
 <footer>AI Caller · 0.1.0 <span>Контроль каждого разговора</span></footer></div></main>
 {modal&&<div className="overlay"><section className="modal" role="dialog" aria-modal="true"><div className="modal-title"><h2>{modal==='create'?'Новая запись':modal==='import'?'Импорт контактов':modal==='enroll'?'Добавить в кампанию':'Подробности'}</h2><button aria-label="Закрыть" onClick={()=>setModal(null)}><X size={20}/></button></div>{error&&<div className="error">{error}</div>}
 {modal==='create'&&<form onSubmit={save}>{section!=='callbacks'&&<label>Название / имя<input name="name" required maxLength={200}/></label>}
 {section==='companies'&&<label>Примечания<textarea name="notes"/></label>}
 {section==='contacts'&&<><label>Телефон<input name="phone" required placeholder="+79991234567"/></label><label>Компания<select name="company_id"><option value="">Без компании</option>{options.companies?.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Должность<input name="position"/></label><label>Основание для звонка<textarea name="consent_basis" placeholder="Без основания контакт нельзя добавить в обзвон"/></label></>}
 {section==='scenarios'&&<><label>Цель разговора<textarea name="goal" required/></label><label>Инструкции и стиль речи<textarea name="instructions"/></label>{[['required_questions','Обязательные вопросы'],['optional_questions','Дополнительные вопросы'],['allowed_topics','Допустимые темы'],['forbidden_topics','Запрещённые темы']].map(([key,label])=><label key={key}>{label}<textarea name={key} placeholder="По одному пункту на строку"/></label>)}</>}
 {section==='agents'&&<><label>Роль<input name="role" defaultValue="Помощник"/></label><label>Голос<input name="voice" defaultValue="marin"/></label><label>Инструкции<textarea name="instructions" defaultValue="Говори кратко и естественно по-русски."/></label></>}
 {section==='campaigns'&&<>{[['scenario_id','Сценарий','scenarios'],['agent_id','Агент','agents']].map(([key,label,collection])=><label key={key}>{label}<select name={key} required><option value="">Выберите</option>{options[collection]?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>)}<div className="form-grid">{[['max_concurrent','Одновременных звонков',1,20],['delay_seconds','Пауза между звонками, с',10,3600],['max_attempts','Максимум попыток',2,5],['max_errors','Остановка после ошибок',3,100],['start_hour','Начало, час',9,23],['end_hour','Окончание, час',18,24]].map(([key,label,value,max])=><label key={key}>{label}<input name={String(key)} type="number" min={key==='start_hour'?0:1} max={Number(max)} defaultValue={value}/></label>)}</div><label>Часовой пояс<input name="timezone" defaultValue={Intl.DateTimeFormat().resolvedOptions().timeZone}/></label><p>Расписание: понедельник–пятница. Режим: симуляция.</p></>}
 {section==='callbacks'&&<><label>Контакт<select name="contact_id" required>{options.contacts?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Дата и время (ваш часовой пояс)<input name="scheduled_at" type="datetime-local" required/></label><label>Примечание<textarea name="notes"/></label><p>Перезвон сохраняется как задача оператору, без автоматического набора.</p></>}
 <button className="primary" disabled={busy}>Сохранить</button></form>}
 {modal==='enroll'&&<form onSubmit={e=>{e.preventDefault();const ids=new FormData(e.currentTarget).getAll('contacts');run(async()=>{await api('/campaigns/'+selected?.id+'/contacts','POST',{contact_ids:ids});setModal(null);await load()})}}>{options.contacts?.map(x=><label className="check" key={x.id}><input type="checkbox" name="contacts" value={x.id} disabled={x.opted_out||!x.consent_basis}/>{x.name} · {x.phone}{x.opted_out?' · отказ':!x.consent_basis?' · нет основания':''}</label>)}<button className="primary" disabled={busy}>Добавить выбранных</button></form>}
 {modal==='import'&&<><p>Колонки: name, phone, position, consent_basis. UTF-8 CSV или XLSX, до 5 МБ.</p><input type="file" accept=".csv,.xlsx" onChange={e=>{setImportFile(e.target.files?.[0]||null);setPreview(null)}}/><button disabled={busy||!importFile} onClick={()=>importContacts()}>Проверить файл</button>{preview&&<><p>Корректных строк: {preview.valid_count}. Ошибок: {preview.errors.length}.</p><pre>{JSON.stringify(preview.errors,null,2)}</pre><button className="primary" disabled={busy||preview.errors.length>0} onClick={()=>importContacts(true)}>Подтвердить импорт</button></>}</>}
 {modal==='detail'&&selected&&<>{selected.messages?<><Badge value={selected.call.status}/><h3>Транскрипция</h3>{selected.messages.map((x:Row)=><div className={'message '+x.role} key={x.id}><small>{x.role==='user'?'Собеседник':'Агент'} · {fmt(x.created_at)}</small><p>{x.text}</p></div>)}<h3>Результат</h3><pre>{JSON.stringify(selected.call.result,null,2)}</pre></>:selected.contact?<><h3>{selected.contact.name}</h3><p>{selected.contact.phone}</p><p>Основание: {selected.contact.consent_basis||'Не указано'}</p>{canWrite&&<button disabled={busy} onClick={()=>run(async()=>{await api('/contacts/'+selected.contact.id+'/opt-out','POST');setModal(null);await load()})}>Исключить из обзвона</button>}{user.role==='admin'&&<button className="danger" onClick={()=>{if(window.confirm('Удалить контакт и историю разговоров? Отказ от звонков сохранится.'))run(async()=>{await api('/contacts/'+selected.contact.id,'DELETE');setModal(null);await load()})}}>Удалить контакт и историю</button>}<h3>История звонков</h3>{selected.calls.map((c:Row)=><p key={c.id}>{fmt(c.created_at)} · <Badge value={c.status}/></p>)}</>:<pre>{JSON.stringify(selected,null,2)}</pre>}</>}
 </section></div>}
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
